"use client";

import { useEffect, useMemo, useState, type ChangeEvent } from "react";
import { agencyApi, formatDate, formatMoney } from "@/lib/agency/api";

const box: React.CSSProperties = { background: "var(--card,#fff)", border: "1px solid var(--border,#e5e7eb)", borderRadius: 14, padding: 18, marginBottom: 16 };
const grid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 12 };

type Audit = { id: string; actorEmail?: string; action: string; entityType?: string; entityId?: string; requestPath?: string; changes?: unknown; createdAt: string };
export function AuditPage({ show }: { show: boolean }) {
  const [items, setItems] = useState<Audit[]>([]); const [total, setTotal] = useState(0); const [err, setErr] = useState("");
  const [actor, setActor] = useState(""); const [action, setAction] = useState(""); const [entityType, setEntityType] = useState("");
  async function load() {
    const q = new URLSearchParams({ limit: "100" }); if (actor) q.set("actor", actor); if (action) q.set("action", action); if (entityType) q.set("entityType", entityType);
    const r = await agencyApi<{ items: Audit[]; total: number }>(`/crm/audit?${q}`);
    if (r.success) { setItems(r.data.items); setTotal(r.data.total); setErr(""); } else setErr(r.message || "Audit tarixini olib bo‘lmadi");
  }
  useEffect(() => { if (show) void load(); }, [show]);
  return <section className={`view crm-competition${show ? " active" : ""}`}>
    <div style={box}><h3>O‘zgarishlar tarixi</h3><p className="muted">Kim, qachon va qaysi ma’lumotni o‘zgartirganini tekshiring. Faqat agentlik egasi ko‘ra oladi.</p>
      <div className="crm-filter-grid">
        <label className="crm-filter-field"><span>Xodim</span><input value={actor} onChange={(e) => setActor(e.target.value)} placeholder="Xodim emaili" /></label>
        <label className="crm-filter-field"><span>Amal</span><input value={action} onChange={(e) => setAction(e.target.value)} placeholder="PATCH, POST..." /></label>
        <label className="crm-filter-field"><span>Bo‘lim</span><select value={entityType} onChange={(e) => setEntityType(e.target.value)}><option value="">Barcha bo‘limlar</option>{["bookings","leads","tasks","documents","team","telegram","instagram","whatsapp","crm"].map((x)=><option key={x}>{x}</option>)}</select></label>
        <button className="btn btn-primary crm-filter-submit" onClick={() => void load()}>Filtrlash</button>
      </div>
    </div>
    {err ? <div className="note">{err}</div> : <div style={box}><b>{total} ta yozuv</b><div style={{overflowX:"auto",marginTop:12}}><table className="tbl"><thead><tr><th>Vaqt</th><th>Xodim</th><th>Amal</th><th>Bo‘lim</th><th>Manzil</th></tr></thead><tbody>{items.map((x)=><tr key={x.id}><td>{formatDate(x.createdAt)}</td><td>{x.actorEmail || "Tizim"}</td><td><b>{x.action}</b></td><td>{x.entityType || "—"}</td><td><small>{x.requestPath || "—"}</small></td></tr>)}</tbody></table></div></div>}
  </section>;
}

const CSV_FIELDS: Record<string,string> = { customerName:"Mijoz ismi *",customerPhone:"Telefon",customerEmail:"Email",leadTour:"Tur",leadCity:"Shahar",travelers:"Sayyohlar",travelDate:"Safar sanasi",totalEstimate:"Summa",currency:"Valyuta",pipelineStage:"Bosqich",message:"Izoh",leadTelegram:"Telegram",leadWhatsapp:"WhatsApp",customerBirthday:"Tug‘ilgan kun",assignedEmail:"Menejer emaili" };
type CsvPreview = { headers:string[]; suggestedMapping:Record<string,string>; preview:{row:number;status:string;customerName:string;customerPhone?:string;customerEmail?:string}[]; totalRows:number;readyRows:number;duplicateRows:number;invalidRows:number;warnings:string[] };
type ImportBatch = { id:string;fileName?:string;status:string;totalRows:number;importedRows:number;duplicateRows:number;invalidRows:number;createdAt:string };
export function CsvImportPage({ show, readOnly, onImported }: { show:boolean;readOnly:boolean;onImported:()=>Promise<unknown>|void }) {
  const [csv,setCsv]=useState(""); const [fileName,setFileName]=useState(""); const [mapping,setMapping]=useState<Record<string,string>>({}); const [preview,setPreview]=useState<CsvPreview|null>(null); const [batches,setBatches]=useState<ImportBatch[]>([]); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
  async function loadBatches(){ const r=await agencyApi<{items:ImportBatch[]}>("/crm/imports"); if(r.success)setBatches(r.data.items); }
  useEffect(()=>{if(show)void loadBatches();},[show]);
  async function choose(file?:File){if(!file)return;setFileName(file.name);setCsv(await file.text());setPreview(null);setMsg("");}
  async function doPreview(){setBusy(true);const r=await agencyApi<CsvPreview>("/crm/import/csv/preview",{method:"POST",body:JSON.stringify({csv,mapping})});setBusy(false);if(r.success){setPreview(r.data);setMapping((m)=>Object.keys(m).length?m:r.data.suggestedMapping);setMsg("");}else setMsg(r.message||"Preview xatosi");}
  async function commit(){setBusy(true);const r=await agencyApi<{imported:number}>("/crm/import/csv/commit",{method:"POST",body:JSON.stringify({csv,mapping,fileName})});setBusy(false);if(r.success){setMsg(`${r.data.imported} ta lid import qilindi.`);setPreview(null);setCsv("");await Promise.all([loadBatches(),onImported()]);}else setMsg(r.message||"Import xatosi");}
  async function rollback(id:string){if(!window.confirm("Faqat shu CSV batch yaratgan lidlar o‘chiriladi. Qaytarilsinmi?"))return;const r=await agencyApi<{deleted:number}>(`/crm/imports/${id}/rollback`,{method:"POST"});if(r.success){setMsg(`${r.data.deleted} ta import lid qaytarildi.`);await Promise.all([loadBatches(),onImported()]);}else setMsg(r.message||"Rollback xatosi");}
  return <section className={`view${show?" active":""}`}><div style={box}><h3>Xavfsiz CSV import</h3><p className="muted">1) Faylni tanlang. 2) Preview qiling. 3) Ustunlarni tekshiring. 4) Importni tasdiqlang.</p><input type="file" accept=".csv,text/csv" disabled={readOnly} onChange={(e)=>void choose(e.target.files?.[0])}/>{csv?<button className="btn btn-primary" disabled={busy} onClick={()=>void doPreview()} style={{marginLeft:10}}>{busy?"Tekshirilmoqda…":"Preview"}</button>:null}{msg?<p>{msg}</p>:null}</div>
    {preview?<><div style={box}><h3>Ustunlarni moslashtirish</h3><div style={grid}>{Object.entries(CSV_FIELDS).map(([key,label])=><label key={key} className="fld"><span>{label}</span><select value={mapping[key]||""} onChange={(e)=>setMapping({...mapping,[key]:e.target.value})}><option value="">— ishlatilmasin —</option>{preview.headers.map((h)=><option key={h} value={h}>{h}</option>)}</select></label>)}</div><div style={{...grid,marginTop:15}}><b>Jami: {preview.totalRows}</b><b style={{color:"#16845b"}}>Tayyor: {preview.readyRows}</b><b style={{color:"#b7791f"}}>Dublikat: {preview.duplicateRows}</b><b style={{color:"#c53030"}}>Xato: {preview.invalidRows}</b></div><button className="btn btn-primary" disabled={busy||readOnly||!mapping.customerName||preview.readyRows===0} onClick={()=>void commit()} style={{marginTop:16}}>Importni tasdiqlash</button></div>
      <div style={box}><h3>Preview</h3><div style={{overflowX:"auto"}}><table className="tbl"><thead><tr><th>Qator</th><th>Holat</th><th>Mijoz</th><th>Telefon</th><th>Email</th></tr></thead><tbody>{preview.preview.map((x)=><tr key={x.row}><td>{x.row}</td><td>{x.status==="ready"?"Tayyor":x.status==="duplicate_db"?"Bazadagi dublikat":"Fayldagi dublikat"}</td><td>{x.customerName}</td><td>{x.customerPhone||"—"}</td><td>{x.customerEmail||"—"}</td></tr>)}</tbody></table></div></div></>:null}
    <div style={box}><h3>Import tarixi</h3>{batches.length===0?<p className="muted">Hali import qilinmagan.</p>:<div style={{overflowX:"auto"}}><table className="tbl"><thead><tr><th>Fayl</th><th>Vaqt</th><th>Import</th><th>Dublikat</th><th>Holat</th><th/></tr></thead><tbody>{batches.map((x)=><tr key={x.id}><td>{x.fileName||"import.csv"}</td><td>{formatDate(x.createdAt)}</td><td>{x.importedRows}</td><td>{x.duplicateRows}</td><td>{x.status==="rolled_back"?"Qaytarilgan":"Faol"}</td><td>{x.status!=="rolled_back"?<button className="btn btn-ghost btn-sm" disabled={readOnly} onClick={()=>void rollback(x.id)}>Qaytarish</button>:null}</td></tr>)}</tbody></table></div>}</div>
  </section>;
}

type Insights={periodDays:number;settings:{firstResponseMinutes:number;autoAssignEnabled:boolean;reminderEnabled:boolean};totals:{leads:number;won:number;lost:number;unanswered:number;slaBreached:number;avgResponseMinutes:number|null};managers:{memberId?:string;name:string;leads:number;won:number;completed:number;lost:number;revenue:number;conversionPct:number;avgResponseMinutes:number|null}[]};
export function InsightsPage({show,readOnly}:{show:boolean;readOnly:boolean}){
  const [days,setDays]=useState(30);const [d,setD]=useState<Insights|null>(null);const [msg,setMsg]=useState("");
  async function load(){const r=await agencyApi<Insights>(`/crm/insights?days=${days}`);if(r.success){setD(r.data);setMsg("");}else setMsg(r.message||"Hisobot olinmadi");}
  useEffect(()=>{if(show)void load();},[show,days]);
  async function save(){if(!d)return;const r=await agencyApi<{settings:Insights["settings"]}>("/crm/settings",{method:"PUT",body:JSON.stringify(d.settings)});setMsg(r.success?"SLA sozlamalari saqlandi.":r.message||"Saqlanmadi");if(r.success)void load();}
  const kpis=useMemo(()=>d?[['Yangi lidlar',d.totals.leads],['Yopilgan',d.totals.won],['Javobsiz SLA',d.totals.unanswered],['O‘rtacha javob',d.totals.avgResponseMinutes==null?'—':`${d.totals.avgResponseMinutes} daq.`]]:[],[d]);
  return <section className={`view${show?" active":""}`}>{msg?<div className="note">{msg}</div>:null}<div style={box}><div style={{display:"flex",gap:12,justifyContent:"space-between",alignItems:"center",flexWrap:"wrap"}}><div><h3>SLA va menejer KPI</h3><p className="muted">Javobsiz lidlarni aniqlaydi, vazifa yaratadi va sotuv natijasini o‘lchaydi.</p></div><select value={days} onChange={(e)=>setDays(Number(e.target.value))}><option value={7}>7 kun</option><option value={30}>30 kun</option><option value={90}>90 kun</option><option value={365}>1 yil</option></select></div></div>{d?<><div style={grid}>{kpis.map(([a,b])=><div style={box} key={String(a)}><small>{a}</small><h2>{b}</h2></div>)}</div><div style={box}><h3>Avtomatlashtirish</h3><div style={grid}><label className="fld"><span>Birinchi javob SLA (daqiqa)</span><input type="number" min={5} max={1440} value={d.settings.firstResponseMinutes} onChange={(e)=>setD({...d,settings:{...d.settings,firstResponseMinutes:Number(e.target.value)}})}/></label><label><input type="checkbox" checked={d.settings.autoAssignEnabled} onChange={(e)=>setD({...d,settings:{...d.settings,autoAssignEnabled:e.target.checked}})}/> Yangi lidlarni round-robin biriktirish</label><label><input type="checkbox" checked={d.settings.reminderEnabled} onChange={(e)=>setD({...d,settings:{...d.settings,reminderEnabled:e.target.checked}})}/> SLA buzilganda vazifa yaratish</label></div><button className="btn btn-primary" disabled={readOnly} onClick={()=>void save()}>Sozlamalarni saqlash</button></div><div style={box}><h3>Menejerlar samaradorligi</h3><div style={{overflowX:"auto"}}><table className="tbl"><thead><tr><th>Menejer</th><th>Lid</th><th>Yopilgan</th><th>Yo‘qotilgan</th><th>Konversiya</th><th>Javob</th><th>Aylanma</th></tr></thead><tbody>{d.managers.map((m)=><tr key={m.memberId||"none"}><td><b>{m.name}</b></td><td>{m.leads}</td><td>{m.won+m.completed}</td><td>{m.lost}</td><td>{m.conversionPct}%</td><td>{m.avgResponseMinutes==null?"—":`${m.avgResponseMinutes} daq.`}</td><td>{formatMoney(m.revenue)}</td></tr>)}</tbody></table></div></div></>:null}</section>;
}

type AutoCondition={field:string;operator:string;value:string};
type AutoAction={id?:string;type:string;config:Record<string,string|number>};
type AutoRule={id:string;name:string;active:boolean;triggerType:string;triggerConfig:Record<string,string|number>;conditionMode:"all"|"any";conditions:AutoCondition[];maxAttempts:number;actions:AutoAction[];lastRunAt?:string;createdAt:string;_count?:{runs:number}};
type AutoRun={id:string;status:string;attempt:number;entityType:string;entityId:string;error?:string;createdAt:string;finishedAt?:string;rule:{name:string}};
type AutoPayload={rules:AutoRule[];runs:AutoRun[];metadata:{triggers:string[];actions:string[];conditionFields:string[];operators:string[];stages:string[]}};
type AutoDraft=Omit<AutoRule,"id"|"lastRunAt"|"createdAt"|"_count"> & {id?:string};
const TRIGGER_LABEL:Record<string,string>={lead_created:"Yangi lid yaratildi",lead_unanswered:"Lidga javob berilmadi",stage_changed:"Lid bosqichga o‘tdi",payment_overdue:"To‘lov muddati o‘tdi",document_signed:"Hujjat imzolandi"};
const ACTION_LABEL:Record<string,string>={create_task:"Vazifa yaratish",assign_manager:"Menejer biriktirish",move_stage:"Bosqichni o‘zgartirish",add_tag:"Teg qo‘shish",send_email:"Email yuborish"};
const FIELD_LABEL:Record<string,string>={stage:"Lid bosqichi",source:"Lid manbasi",assignedMemberId:"Menejer",currency:"Valyuta",amount:"Summa",direction:"Kirim/chiqim",status:"Holat",customerName:"Mijoz ismi"};
const OPERATOR_LABEL:Record<string,string>={equals:"Teng",not_equals:"Teng emas",contains:"Ichida mavjud",greater_or_equal:"Katta yoki teng",less_or_equal:"Kichik yoki teng",is_empty:"Bo‘sh",not_empty:"Bo‘sh emas"};
const STAGE_LABEL_AUTO:Record<string,string>={new:"Yangi",contacted:"Bog‘lanildi",quoted:"Taklif yuborildi",won:"Kelishildi",completed:"Yakunlandi",lost:"Yo‘qotildi"};
const newDraft=():AutoDraft=>({name:"",active:true,triggerType:"lead_created",triggerConfig:{minutes:30,stage:"won"},conditionMode:"all",conditions:[],maxAttempts:3,actions:[{type:"create_task",config:{title:"{customerName} bilan bog‘lanish",dueMinutes:0}}]});
function copyRule(rule:AutoRule):AutoDraft{return JSON.parse(JSON.stringify(rule));}

function ActionConfig({action,onChange,stages}:{action:AutoAction;onChange:(v:AutoAction)=>void;stages:string[]}){
  const set=(key:string)=>(e:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>onChange({...action,config:{...action.config,[key]:e.target.type==="number"?Number(e.target.value):e.target.value}});
  if(action.type==="create_task")return <div style={grid}><label className="fld"><span>Vazifa nomi</span><input value={String(action.config.title||"")} onChange={set("title")} placeholder="{customerName} bilan bog‘lanish"/></label><label className="fld"><span>Muddati (daqiqadan keyin)</span><input type="number" min={0} value={Number(action.config.dueMinutes||0)} onChange={set("dueMinutes")}/></label></div>;
  if(action.type==="move_stage")return <label className="fld"><span>Yangi bosqich</span><select value={String(action.config.stage||"contacted")} onChange={set("stage")}>{stages.map(x=><option key={x} value={x}>{STAGE_LABEL_AUTO[x]||x}</option>)}</select></label>;
  if(action.type==="add_tag")return <label className="fld"><span>Teg nomi</span><input value={String(action.config.name||"")} onChange={set("name")} placeholder="Issiq lid"/></label>;
  if(action.type==="send_email")return <div style={grid}><label className="fld"><span>Qabul qiluvchi</span><select value={String(action.config.recipient||"customer")} onChange={set("recipient")}><option value="customer">Mijoz</option><option value="owner">Agentlik egasi</option></select></label><label className="fld"><span>Mavzu</span><input value={String(action.config.subject||"")} onChange={set("subject")}/></label><label className="fld" style={{gridColumn:"1/-1"}}><span>Xabar</span><textarea rows={3} value={String(action.config.body||"")} onChange={set("body")} placeholder="Hurmatli {customerName}..."/></label></div>;
  return <p className="muted">Faol menejerlar orasidan round-robin usulida biriktiriladi.</p>;
}

export function AutomationPage({show,readOnly}:{show:boolean;readOnly:boolean}){
  const [data,setData]=useState<AutoPayload|null>(null);const [draft,setDraft]=useState<AutoDraft|null>(null);const [msg,setMsg]=useState("");const [busy,setBusy]=useState("");
  async function load(){const r=await agencyApi<AutoPayload>("/crm/automation");if(r.success){setData(r.data);setMsg("");}else setMsg(r.message||"Avtomatizatsiya olinmadi");}
  useEffect(()=>{if(show)void load();},[show]);
  const meta=data?.metadata||{triggers:Object.keys(TRIGGER_LABEL),actions:Object.keys(ACTION_LABEL),conditionFields:Object.keys(FIELD_LABEL),operators:Object.keys(OPERATOR_LABEL),stages:Object.keys(STAGE_LABEL_AUTO)};
  function setAction(index:number,value:AutoAction){if(!draft)return;setDraft({...draft,actions:draft.actions.map((x,i)=>i===index?value:x)});}
  async function save(){if(!draft)return;setBusy("save");const r=await agencyApi(draft.id?`/crm/automation/rules/${draft.id}`:"/crm/automation/rules",{method:draft.id?"PUT":"POST",body:JSON.stringify(draft)});setBusy("");setMsg(r.success?"Avtomatizatsiya saqlandi.":r.message||"Saqlanmadi");if(r.success){setDraft(null);await load();}}
  async function remove(id:string){if(!confirm("Qoida va uning run tarixi o‘chiriladi. Davom etilsinmi?"))return;const r=await agencyApi(`/crm/automation/rules/${id}`,{method:"DELETE"});setMsg(r.success?"Qoida o‘chirildi.":r.message||"O‘chirilmadi");if(r.success)await load();}
  async function run(id:string){setBusy(id);const r=await agencyApi(`/crm/automation/rules/${id}/run`,{method:"POST"});setBusy("");setMsg(r.success?"Qoida mos oxirgi ma’lumotda bajarildi.":r.message||"Ishga tushmadi");await load();}
  async function retry(id:string){setBusy(id);const r=await agencyApi(`/crm/automation/runs/${id}/retry`,{method:"POST"});setBusy("");setMsg(r.success?"Qayta urinish bajarildi.":r.message||"Qayta urinilmadi");await load();}
  async function toggle(rule:AutoRule){setBusy(rule.id);const r=await agencyApi(`/crm/automation/rules/${rule.id}`,{method:"PUT",body:JSON.stringify({...rule,active:!rule.active})});setBusy("");if(!r.success)setMsg(r.message||"Holat o‘zgarmadi");await load();}
  return <section className={`view${show?" active":""}`}>{msg?<div className="note" style={{marginBottom:12}}>{msg}</div>:null}<div style={box}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h3>No-code avtomatizatsiya</h3><p className="muted">Trigger → shart → amal. Qoidalar har 5 daqiqada tekshiriladi, xato bo‘lsa avtomatik retry qilinadi.</p></div><button className="btn btn-primary" disabled={readOnly} onClick={()=>setDraft(newDraft())}>+ Yangi qoida</button></div></div>
    {draft?<div style={box}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h3>{draft.id?"Qoidani tahrirlash":"Yangi avtomatizatsiya"}</h3><button className="btn btn-ghost btn-sm" onClick={()=>setDraft(null)}>Yopish</button></div><div style={grid}><label className="fld"><span>Qoida nomi</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Yangi lidga vazifa"/></label><label className="fld"><span>Trigger</span><select value={draft.triggerType} onChange={e=>setDraft({...draft,triggerType:e.target.value})}>{meta.triggers.map(x=><option key={x} value={x}>{TRIGGER_LABEL[x]||x}</option>)}</select></label>{draft.triggerType==="lead_unanswered"?<label className="fld"><span>Necha daqiqadan keyin</span><input type="number" min={5} value={Number(draft.triggerConfig.minutes||30)} onChange={e=>setDraft({...draft,triggerConfig:{...draft.triggerConfig,minutes:Number(e.target.value)}})}/></label>:null}{draft.triggerType==="stage_changed"?<label className="fld"><span>Qaysi bosqich</span><select value={String(draft.triggerConfig.stage||"won")} onChange={e=>setDraft({...draft,triggerConfig:{...draft.triggerConfig,stage:e.target.value}})}>{meta.stages.map(x=><option key={x} value={x}>{STAGE_LABEL_AUTO[x]||x}</option>)}</select></label>:null}<label className="fld"><span>Xatoda urinishlar</span><input type="number" min={1} max={5} value={draft.maxAttempts} onChange={e=>setDraft({...draft,maxAttempts:Number(e.target.value)})}/></label></div>
      <h4 style={{marginTop:18}}>Shartlar</h4><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:10}}><span className="muted">Shartlar rejimi:</span><select value={draft.conditionMode} onChange={e=>setDraft({...draft,conditionMode:e.target.value as "all"|"any"})}><option value="all">Barchasi mos</option><option value="any">Kamida bittasi mos</option></select><button className="btn btn-ghost btn-sm" onClick={()=>setDraft({...draft,conditions:[...draft.conditions,{field:"stage",operator:"equals",value:"new"}]})}>+ Shart</button></div>{draft.conditions.map((condition,index)=><div key={index} style={{...grid,marginBottom:8}}><select value={condition.field} onChange={e=>setDraft({...draft,conditions:draft.conditions.map((x,i)=>i===index?{...x,field:e.target.value}:x)})}>{meta.conditionFields.map(x=><option key={x} value={x}>{FIELD_LABEL[x]||x}</option>)}</select><select value={condition.operator} onChange={e=>setDraft({...draft,conditions:draft.conditions.map((x,i)=>i===index?{...x,operator:e.target.value}:x)})}>{meta.operators.map(x=><option key={x} value={x}>{OPERATOR_LABEL[x]||x}</option>)}</select>{!["is_empty","not_empty"].includes(condition.operator)?<input value={condition.value} onChange={e=>setDraft({...draft,conditions:draft.conditions.map((x,i)=>i===index?{...x,value:e.target.value}:x)})} placeholder="Qiymat"/>:<span/>}<button className="btn btn-ghost btn-sm" onClick={()=>setDraft({...draft,conditions:draft.conditions.filter((_,i)=>i!==index)})}>Olib tashlash</button></div>)}
      <h4 style={{marginTop:18}}>Amallar</h4>{draft.actions.map((action,index)=><div key={index} style={{border:"1px solid var(--border,#e5e7eb)",borderRadius:12,padding:14,marginBottom:10}}><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:10}}><b>{index+1}.</b><select value={action.type} onChange={e=>setAction(index,{type:e.target.value,config:{}})}>{meta.actions.map(x=><option key={x} value={x}>{ACTION_LABEL[x]||x}</option>)}</select><button className="btn btn-ghost btn-sm" disabled={draft.actions.length===1} onClick={()=>setDraft({...draft,actions:draft.actions.filter((_,i)=>i!==index)})}>Olib tashlash</button></div><ActionConfig action={action} onChange={value=>setAction(index,value)} stages={meta.stages}/></div>)}<button className="btn btn-ghost btn-sm" onClick={()=>setDraft({...draft,actions:[...draft.actions,{type:"create_task",config:{title:"{customerName} bilan bog‘lanish",dueMinutes:0}}]})}>+ Amal qo‘shish</button><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:16}}><label><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Faol</label><button className="btn btn-primary" disabled={busy==="save"||!draft.name.trim()} onClick={()=>void save()}>{busy==="save"?"Saqlanmoqda…":"Saqlash"}</button></div></div>:null}
    <div style={box}><h3>Qoidalar</h3>{!data?.rules.length?<p className="muted">Hali qoida yaratilmagan.</p>:<div style={{display:"grid",gap:10}}>{data.rules.map(rule=><div key={rule.id} style={{border:"1px solid var(--border,#e5e7eb)",borderRadius:12,padding:14,display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><b>{rule.name}</b><div className="muted">{TRIGGER_LABEL[rule.triggerType]||rule.triggerType} → {rule.actions.map(x=>ACTION_LABEL[x.type]||x.type).join(" → ")} · {rule._count?.runs||0} run</div></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button className={`btn btn-sm ${rule.active?"btn-primary":"btn-ghost"}`} disabled={readOnly||busy===rule.id} onClick={()=>void toggle(rule)}>{rule.active?"Faol":"To‘xtatilgan"}</button><button className="btn btn-ghost btn-sm" disabled={readOnly||busy===rule.id} onClick={()=>void run(rule.id)}>Hozir bajarish</button><button className="btn btn-ghost btn-sm" disabled={readOnly} onClick={()=>setDraft(copyRule(rule))}>Tahrirlash</button><button className="btn btn-ghost btn-sm" disabled={readOnly} onClick={()=>void remove(rule.id)}>O‘chirish</button></div></div>)}</div>}</div>
    <div style={box}><h3>Bajarilish jurnali</h3>{!data?.runs.length?<p className="muted">Run tarixi hali yo‘q.</p>:<div style={{overflowX:"auto"}}><table className="tbl"><thead><tr><th>Vaqt</th><th>Qoida</th><th>Entity</th><th>Holat</th><th>Urinish</th><th>Xato</th><th/></tr></thead><tbody>{data.runs.map(run=><tr key={run.id}><td>{formatDate(run.createdAt)}</td><td><b>{run.rule.name}</b></td><td>{run.entityType}</td><td>{run.status==="success"?"Bajarildi":run.status==="failed"?"Xato":run.status}</td><td>{run.attempt}</td><td><small>{run.error||"—"}</small></td><td>{run.status==="failed"?<button className="btn btn-ghost btn-sm" disabled={readOnly||busy===run.id} onClick={()=>void retry(run.id)}>Qayta urinish</button>:null}</td></tr>)}</tbody></table></div>}</div></section>;
}

type IntegrationKey={id:string;name:string;keyPrefix:string;scopes:string[];rateLimitPerMinute:number;lastUsedAt?:string;expiresAt?:string;revokedAt?:string;createdAt:string};
type WebhookEndpoint={id:string;name:string;url:string;active:boolean;events:string[];secretPrefix:string;maxAttempts:number;lastSuccessAt?:string;lastFailureAt?:string;createdAt:string;_count:{deliveries:number}};
type WebhookDelivery={id:string;status:string;attempt:number;maxAttempts:number;responseStatus?:number;error?:string;durationMs?:number;createdAt:string;endpoint:{id:string;name:string};event:{id:string;type:string;entityType?:string;entityId?:string;createdAt:string}};
type IntegrationPayload={apiKeys:IntegrationKey[];endpoints:WebhookEndpoint[];deliveries:WebhookDelivery[];metadata:{scopes:string[];events:string[];publicBaseUrl:string}};
const SCOPE_LABEL:Record<string,string>={"leads:read":"Lidlarni o‘qish","leads:write":"Lid yaratish va tahrirlash","tours:read":"Turlarni o‘qish","finance:read":"Moliyani o‘qish"};
const EVENT_LABEL:Record<string,string>={"*":"Barcha hodisalar","webhook.test":"Test","lead.created":"Lid yaratildi","lead.updated":"Lid yangilandi","lead.stage_changed":"Lid bosqichi o‘zgardi","task.created":"Vazifa yaratildi","finance.updated":"Moliya yangilandi","document.updated":"Hujjat yangilandi","automation.updated":"Avtomatizatsiya yangilandi","agency.updated":"Agentlik yangilandi"};

export function IntegrationPage({show,readOnly}:{show:boolean;readOnly:boolean}){
  const [data,setData]=useState<IntegrationPayload|null>(null);const [msg,setMsg]=useState("");const [revealed,setRevealed]=useState("");const [busy,setBusy]=useState("");
  const [keyName,setKeyName]=useState("CRM integratsiyasi");const [scopes,setScopes]=useState<string[]>(["leads:read","leads:write","tours:read"]);
  const [hookName,setHookName]=useState("Asosiy webhook");const [hookUrl,setHookUrl]=useState("");const [events,setEvents]=useState<string[]>(["webhook.test","lead.created","lead.updated","lead.stage_changed"]);
  async function load(){const r=await agencyApi<IntegrationPayload>("/crm/integrations");if(r.success){setData(r.data);setMsg("");}else setMsg(r.message||"Integratsiyalar olinmadi");}
  useEffect(()=>{if(show)void load();},[show]);
  const toggle=(value:string,items:string[],set:(rows:string[])=>void)=>set(items.includes(value)?items.filter(x=>x!==value):[...items,value]);
  async function createKey(){setBusy("key");const r=await agencyApi<{rawKey:string}>("/crm/integrations/api-keys",{method:"POST",body:JSON.stringify({name:keyName,scopes})});setBusy("");if(r.success){setRevealed(r.data.rawKey);setMsg("API kalit yaratildi. U faqat hozir bir marta ko‘rsatiladi.");await load();}else setMsg(r.message||"API kalit yaratilmadi");}
  async function revokeKey(id:string){if(!confirm("API kalit bekor qilinsinmi? Uni qayta tiklab bo‘lmaydi."))return;const r=await agencyApi(`/crm/integrations/api-keys/${id}`,{method:"DELETE"});setMsg(r.success?"API kalit bekor qilindi.":r.message||"Bekor qilinmadi");await load();}
  async function createHook(){setBusy("hook");const r=await agencyApi<{secret:string}>("/crm/integrations/webhooks",{method:"POST",body:JSON.stringify({name:hookName,url:hookUrl,events,maxAttempts:6})});setBusy("");if(r.success){setRevealed(r.data.secret);setHookUrl("");setMsg("Webhook yaratildi. Signing secret faqat hozir bir marta ko‘rsatiladi.");await load();}else setMsg(r.message||"Webhook yaratilmadi");}
  async function hookAction(id:string,action:"test"|"rotate-secret"){setBusy(id);const r=await agencyApi<{secret?:string}>(`/crm/integrations/webhooks/${id}/${action}`,{method:"POST"});setBusy("");if(r.success){if(r.data.secret)setRevealed(r.data.secret);setMsg(action==="test"?"Test delivery bajarildi. Natijani jurnalda ko‘ring.":"Yangi secret yaratildi va faqat hozir ko‘rsatiladi.");}else setMsg(r.message||"Amal bajarilmadi");await load();}
  async function toggleHook(endpoint:WebhookEndpoint){const r=await agencyApi(`/crm/integrations/webhooks/${endpoint.id}`,{method:"PUT",body:JSON.stringify({...endpoint,active:!endpoint.active})});setMsg(r.success?"Webhook holati yangilandi.":r.message||"Yangilanmadi");await load();}
  async function removeHook(id:string){if(!confirm("Webhook va uning delivery tarixi o‘chirilsinmi?"))return;const r=await agencyApi(`/crm/integrations/webhooks/${id}`,{method:"DELETE"});setMsg(r.success?"Webhook o‘chirildi.":r.message||"O‘chirilmadi");await load();}
  async function retry(id:string){setBusy(id);const r=await agencyApi(`/crm/integrations/deliveries/${id}/retry`,{method:"POST"});setBusy("");setMsg(r.success?"Delivery qayta yuborildi.":r.message||"Qayta yuborilmadi");await load();}
  async function copySecret(){try{await navigator.clipboard.writeText(revealed);setMsg("Maxfiy qiymat nusxalandi.");}catch{setMsg("Nusxalab bo‘lmadi — qiymatni qo‘lda belgilang.");}}
  return <section className={`view${show?" active":""}`}>
    {msg?<div className="note" style={{marginBottom:12}}>{msg}</div>:null}
    {revealed?<div style={{...box,border:"2px solid #eab308"}}><h3>Bir martalik maxfiy qiymat</h3><p className="muted">Hozir xavfsiz joyga saqlang. Sahifa yopilgach qayta ko‘rsatilmaydi.</p><textarea rows={3} readOnly value={revealed}/><div style={{display:"flex",gap:8,marginTop:8}}><button className="btn btn-primary" onClick={()=>void copySecret()}>Nusxalash</button><button className="btn btn-ghost" onClick={()=>setRevealed("")}>Yopish</button></div></div>:null}
    <div style={box}><h3>Public API kalitlari</h3><p className="muted">Base URL: <code>{data?.metadata.publicBaseUrl||"https://travelorai.com/api/v1/public"}</code>. Header: <code>Authorization: Bearer tai_live_…</code></p><div style={grid}><label className="fld"><span>Kalit nomi</span><input value={keyName} onChange={e=>setKeyName(e.target.value)}/></label><div><span>Scope’lar</span><div style={{display:"grid",gap:7,marginTop:8}}>{(data?.metadata.scopes||Object.keys(SCOPE_LABEL)).map(scope=><label key={scope}><input type="checkbox" checked={scopes.includes(scope)} onChange={()=>toggle(scope,scopes,setScopes)}/> {SCOPE_LABEL[scope]||scope}</label>)}</div></div></div><button className="btn btn-primary" disabled={readOnly||busy==="key"||!keyName.trim()||!scopes.length} onClick={()=>void createKey()}>+ API kalit yaratish</button><div style={{overflowX:"auto",marginTop:16}}><table className="tbl"><thead><tr><th>Nomi</th><th>Prefix</th><th>Scope</th><th>Oxirgi ishlatilgan</th><th>Holat</th><th/></tr></thead><tbody>{data?.apiKeys.map(key=><tr key={key.id}><td><b>{key.name}</b></td><td><code>{key.keyPrefix}…</code></td><td><small>{key.scopes.join(", ")}</small></td><td>{key.lastUsedAt?formatDate(key.lastUsedAt):"—"}</td><td>{key.revokedAt?"Bekor qilingan":"Faol"}</td><td>{!key.revokedAt?<button className="btn btn-ghost btn-sm" disabled={readOnly} onClick={()=>void revokeKey(key.id)}>Bekor qilish</button>:null}</td></tr>)}</tbody></table></div></div>
    <div style={box}><h3>Outbound webhook</h3><p className="muted">Har POST so‘rov `X-TravelorAI-Timestamp` va `X-TravelorAI-Signature` bilan imzolanadi. Qabul qiluvchi `HMAC-SHA256(secret, timestamp + "." + rawBody)` orqali tekshiradi.</p><div style={grid}><label className="fld"><span>Nomi</span><input value={hookName} onChange={e=>setHookName(e.target.value)}/></label><label className="fld"><span>HTTPS endpoint</span><input value={hookUrl} onChange={e=>setHookUrl(e.target.value)} placeholder="https://crm.example.com/webhooks/travelorai"/></label></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:7,margin:"12px 0"}}>{(data?.metadata.events||Object.keys(EVENT_LABEL)).map(event=><label key={event}><input type="checkbox" checked={events.includes(event)} onChange={()=>toggle(event,events,setEvents)}/> {EVENT_LABEL[event]||event}</label>)}</div><button className="btn btn-primary" disabled={readOnly||busy==="hook"||!hookName.trim()||!hookUrl.trim()||!events.length} onClick={()=>void createHook()}>+ Webhook qo‘shish</button><div style={{display:"grid",gap:10,marginTop:16}}>{data?.endpoints.map(endpoint=><div key={endpoint.id} style={{border:"1px solid var(--border,#e5e7eb)",borderRadius:12,padding:14}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><b>{endpoint.name}</b><div><code>{endpoint.url}</code></div><small className="muted">{endpoint.events.join(", ")} · secret {endpoint.secretPrefix}… · {endpoint._count.deliveries} delivery</small></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button className={`btn btn-sm ${endpoint.active?"btn-primary":"btn-ghost"}`} disabled={readOnly} onClick={()=>void toggleHook(endpoint)}>{endpoint.active?"Faol":"To‘xtatilgan"}</button><button className="btn btn-ghost btn-sm" disabled={readOnly||busy===endpoint.id} onClick={()=>void hookAction(endpoint.id,"test")}>Test</button><button className="btn btn-ghost btn-sm" disabled={readOnly} onClick={()=>void hookAction(endpoint.id,"rotate-secret")}>Secret almashtirish</button><button className="btn btn-ghost btn-sm" disabled={readOnly} onClick={()=>void removeHook(endpoint.id)}>O‘chirish</button></div></div></div>)}</div></div>
    <div style={box}><h3>Webhook delivery va DLQ jurnali</h3><div style={{overflowX:"auto"}}><table className="tbl"><thead><tr><th>Vaqt</th><th>Endpoint</th><th>Event</th><th>Holat</th><th>Urinish</th><th>HTTP/vaqt</th><th>Xato</th><th/></tr></thead><tbody>{data?.deliveries.map(delivery=><tr key={delivery.id}><td>{formatDate(delivery.createdAt)}</td><td>{delivery.endpoint.name}</td><td><code>{delivery.event.type}</code></td><td>{delivery.status==="dead"?"DLQ":delivery.status}</td><td>{delivery.attempt}/{delivery.maxAttempts}</td><td>{delivery.responseStatus||"—"} · {delivery.durationMs??"—"} ms</td><td><small>{delivery.error||"—"}</small></td><td>{["dead","retry"].includes(delivery.status)?<button className="btn btn-ghost btn-sm" disabled={readOnly||busy===delivery.id} onClick={()=>void retry(delivery.id)}>Qayta yuborish</button>:null}</td></tr>)}</tbody></table></div></div>
  </section>;
}

type WaState={configured:boolean;connected:boolean;displayPhone?:string;phoneNumberId?:string;wabaId?:string;welcome:string};
export function WhatsAppPage({show,readOnly}:{show:boolean;readOnly:boolean}){
  const [st,setSt]=useState<WaState|null>(null);const [token,setToken]=useState("");const [phoneNumberId,setPhone]=useState("");const [wabaId,setWaba]=useState("");const [welcome,setWelcome]=useState("");const [msg,setMsg]=useState("");const [templates,setTemplates]=useState<{id:string;name:string;language:string;status:string;category:string}[]>([]);
  async function load(){const r=await agencyApi<WaState>("/whatsapp");if(r.success){setSt(r.data);setWelcome(r.data.welcome||"");setPhone(r.data.phoneNumberId||"");setWaba(r.data.wabaId||"");}}
  useEffect(()=>{if(show)void load();},[show]);
  async function connect(){const r=await agencyApi<WaState>("/whatsapp/connect",{method:"POST",body:JSON.stringify({token,phoneNumberId,wabaId})});setMsg(r.success?"WhatsApp muvaffaqiyatli ulandi.":r.message||"Ulanmadi");if(r.success){setToken("");void load();}}
  async function disconnect(){if(!confirm("WhatsApp ulanishi uzilsinmi?"))return;const r=await agencyApi("/whatsapp/disconnect",{method:"POST"});setMsg(r.success?"Ulanish uzildi.":r.message||"Xato");void load();}
  async function saveWelcome(){const r=await agencyApi("/whatsapp/welcome",{method:"PUT",body:JSON.stringify({text:welcome})});setMsg(r.success?"Salomlashish saqlandi.":r.message||"Xato");}
  async function loadTemplates(){const r=await agencyApi<{templates:typeof templates}>("/whatsapp/templates");if(r.success)setTemplates(r.data.templates);else setMsg(r.message||"Shablonlar olinmadi");}
  return <section className={`view${show?" active":""}`}><div style={box}><h3>WhatsApp Cloud API</h3><p className="muted">Rasmiy Meta Cloud API. Kelgan xabar avtomatik lidga aylanadi va yagona CRM chatida ko‘rinadi.</p>{msg?<p>{msg}</p>:null}{st?.connected?<><p><b>Ulangan:</b> {st.displayPhone||st.phoneNumberId}</p><button className="btn btn-ghost" disabled={readOnly} onClick={()=>void disconnect()}>Ulanishni uzish</button></>:<div style={grid}><label className="fld"><span>Permanent access token</span><input type="password" value={token} onChange={(e)=>setToken(e.target.value)}/></label><label className="fld"><span>Phone Number ID</span><input value={phoneNumberId} onChange={(e)=>setPhone(e.target.value)}/></label><label className="fld"><span>WABA ID</span><input value={wabaId} onChange={(e)=>setWaba(e.target.value)}/></label><button className="btn btn-primary" disabled={readOnly||!token||!phoneNumberId||!wabaId} onClick={()=>void connect()}>Ulash va webhook’ga obuna bo‘lish</button></div>}</div>{st?.connected?<><div style={box}><h3>Avto-salomlashish</h3><textarea rows={4} value={welcome} onChange={(e)=>setWelcome(e.target.value)} placeholder="Assalomu alaykum! So‘rovingiz qabul qilindi."/><br/><button className="btn btn-primary" disabled={readOnly} onClick={()=>void saveWelcome()}>Saqlash</button></div><div style={box}><h3>Meta shablonlari</h3><button className="btn btn-ghost" onClick={()=>void loadTemplates()}>Yangilash</button>{templates.map((t)=><div key={t.id} style={{padding:"10px 0",borderBottom:"1px solid var(--border,#eee)"}}><b>{t.name}</b> · {t.language} · {t.status} · {t.category}</div>)}</div></>:null}</section>;
}
