"use client";

import { useEffect, useMemo, useState } from "react";
import { agencyApi, formatDate, formatMoney } from "@/lib/agency/api";

const box: React.CSSProperties = { background: "var(--card,#fff)", border: "1px solid var(--border,#e5e7eb)", borderRadius: 14, padding: 18, marginBottom: 16 };
const grid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 12 };

type Audit = { id: string; actorEmail?: string; action: string; entityType?: string; entityId?: string; requestPath?: string; changes?: unknown; createdAt: string };
export function AuditPage({ show }: { show: boolean }) {
  const [items, setItems] = useState<Audit[]>([]); const [total, setTotal] = useState(0); const [err, setErr] = useState("");
  const [actor, setActor] = useState(""); const [action, setAction] = useState(""); const [entityType, setEntityType] = useState("");
  async function load() {
    const q = new URLSearchParams({ limit: "100" }); if (actor) q.set("actor", actor); if (action) q.set("action", action); if (entityType) q.set("entityType", entityType);
    const r = await agencyApi<{ items: Audit[]; total: number }>(`/crm/audit?${q}`);
    if (r.success) { setItems(r.data.items); setTotal(r.data.total); setErr(""); } else setErr(r.message || "Audit tarixini olib bo‘lmadi");
  }
  useEffect(() => { if (show) void load(); }, [show]);
  return <section className={`view${show ? " active" : ""}`}>
    <div style={box}><h3>O‘zgarishlar tarixi</h3><p className="muted">Kim, qachon va qaysi ma’lumotni o‘zgartirganini tekshiring. Faqat agentlik egasi ko‘ra oladi.</p>
      <div style={grid}><input value={actor} onChange={(e) => setActor(e.target.value)} placeholder="Xodim emaili"/><input value={action} onChange={(e) => setAction(e.target.value)} placeholder="Amal: PATCH, POST..."/><select value={entityType} onChange={(e) => setEntityType(e.target.value)}><option value="">Barcha bo‘limlar</option>{["bookings","leads","tasks","documents","team","telegram","instagram","whatsapp","crm"].map((x)=><option key={x}>{x}</option>)}</select><button className="btn btn-primary" onClick={() => void load()}>Filtrlash</button></div>
    </div>
    {err ? <div className="note">{err}</div> : <div style={box}><b>{total} ta yozuv</b><div style={{overflowX:"auto",marginTop:12}}><table className="tbl"><thead><tr><th>Vaqt</th><th>Xodim</th><th>Amal</th><th>Bo‘lim</th><th>Manzil</th></tr></thead><tbody>{items.map((x)=><tr key={x.id}><td>{formatDate(x.createdAt)}</td><td>{x.actorEmail || "Tizim"}</td><td><b>{x.action}</b></td><td>{x.entityType || "—"}</td><td><small>{x.requestPath || "—"}</small></td></tr>)}</tbody></table></div></div>}
  </section>;
}

const CSV_FIELDS: Record<string,string> = { customerName:"Mijoz ismi *",customerPhone:"Telefon",customerEmail:"Email",leadTour:"Tur",leadCity:"Shahar",travelers:"Sayyohlar",travelDate:"Safar sanasi",totalEstimate:"Summa",currency:"Valyuta",pipelineStage:"Bosqich",message:"Izoh",leadTelegram:"Telegram",leadWhatsapp:"WhatsApp",customerBirthday:"Tug‘ilgan kun",assignedEmail:"Menejer emaili" };
type CsvPreview = { headers:string[]; suggestedMapping:Record<string,string>; preview:{row:number;status:string;customerName:string;customerPhone?:string;customerEmail?:string}[]; totalRows:number;readyRows:number;duplicateRows:number;invalidRows:number;warnings:string[] };
type ImportBatch = { id:string;fileName?:string;status:string;totalRows:number;importedRows:number;duplicateRows:number;invalidRows:number;createdAt:string };
export function CsvImportPage({ show, readOnly, onImported }: { show:boolean;readOnly:boolean;onImported:()=>Promise<unknown>|void }) {
  const [csv,setCsv]=useState(""); const [fileName,setFileName]=useState(""); const [mapping,setMapping]=useState<Record<string,string>>({}); const [preview,setPreview]=useState<CsvPreview|null>(null); const [batches,setBatches]=useState<ImportBatch[]>([]); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState("");
  async function loadBatches(){ const r=await agencyApi<{items:ImportBatch[]}>("/crm/imports"); if(r.success)setBatches(r.data.items); }
  useEffect(()=>{if(show)void loadBatches();},[show]);
  async function choose(file?:File){if(!file)return;setFileName(file.name);setCsv(await file.text());setPreview(null);setMsg("");}
  async function doPreview(){setBusy(true);const r=await agencyApi<CsvPreview>("/crm/import/csv/preview",{method:"POST",body:JSON.stringify({csv,mapping})});setBusy(false);if(r.success){setPreview(r.data);setMapping((m)=>Object.keys(m).length?m:r.data.suggestedMapping);setMsg("");}else setMsg(r.message||"Preview xatosi");}
  async function commit(){setBusy(true);const r=await agencyApi<{imported:number}>("/crm/import/csv/commit",{method:"POST",body:JSON.stringify({csv,mapping,fileName})});setBusy(false);if(r.success){setMsg(`${r.data.imported} ta lid import qilindi.`);setPreview(null);setCsv("");await Promise.all([loadBatches(),onImported()]);}else setMsg(r.message||"Import xatosi");}
  async function rollback(id:string){if(!window.confirm("Faqat shu CSV batch yaratgan lidlar o‘chiriladi. Qaytarilsinmi?"))return;const r=await agencyApi<{deleted:number}>(`/crm/imports/${id}/rollback`,{method:"POST"});if(r.success){setMsg(`${r.data.deleted} ta import lid qaytarildi.`);await Promise.all([loadBatches(),onImported()]);}else setMsg(r.message||"Rollback xatosi");}
  return <section className={`view${show?" active":""}`}><div style={box}><h3>Xavfsiz CSV import</h3><p className="muted">1) Faylni tanlang. 2) Preview qiling. 3) Ustunlarni tekshiring. 4) Importni tasdiqlang.</p><input type="file" accept=".csv,text/csv" disabled={readOnly} onChange={(e)=>void choose(e.target.files?.[0])}/>{csv?<button className="btn btn-primary" disabled={busy} onClick={()=>void doPreview()} style={{marginLeft:10}}>{busy?"Tekshirilmoqda…":"Preview"}</button>:null}{msg?<p>{msg}</p>:null}</div>
    {preview?<><div style={box}><h3>Ustunlarni moslashtirish</h3><div style={grid}>{Object.entries(CSV_FIELDS).map(([key,label])=><label key={key} className="fld"><span>{label}</span><select value={mapping[key]||""} onChange={(e)=>setMapping({...mapping,[key]:e.target.value})}><option value="">— ishlatilmasin —</option>{preview.headers.map((h)=><option key={h} value={h}>{h}</option>)}</select></label>)}</div><div style={{...grid,marginTop:15}}><b>Jami: {preview.totalRows}</b><b style={{color:"#16845b"}}>Tayyor: {preview.readyRows}</b><b style={{color:"#b7791f"}}>Dublikat: {preview.duplicateRows}</b><b style={{color:"#c53030"}}>Xato: {preview.invalidRows}</b></div><button className="btn btn-primary" disabled={busy||readOnly||!mapping.customerName||preview.readyRows===0} onClick={()=>void commit()} style={{marginTop:16}}>Importni tasdiqlash</button></div>
      <div style={box}><h3>Preview</h3><div style={{overflowX:"auto"}}><table className="tbl"><thead><tr><th>Qator</th><th>Holat</th><th>Mijoz</th><th>Telefon</th><th>Email</th></tr></thead><tbody>{preview.preview.map((x)=><tr key={x.row}><td>{x.row}</td><td>{x.status==="ready"?"Tayyor":x.status==="duplicate_db"?"Bazadagi dublikat":"Fayldagi dublikat"}</td><td>{x.customerName}</td><td>{x.customerPhone||"—"}</td><td>{x.customerEmail||"—"}</td></tr>)}</tbody></table></div></div></>:null}
    <div style={box}><h3>Import tarixi</h3>{batches.length===0?<p className="muted">Hali import qilinmagan.</p>:<div style={{overflowX:"auto"}}><table className="tbl"><thead><tr><th>Fayl</th><th>Vaqt</th><th>Import</th><th>Dublikat</th><th>Holat</th><th/></tr></thead><tbody>{batches.map((x)=><tr key={x.id}><td>{x.fileName||"import.csv"}</td><td>{formatDate(x.createdAt)}</td><td>{x.importedRows}</td><td>{x.duplicateRows}</td><td>{x.status==="rolled_back"?"Qaytarilgan":"Faol"}</td><td>{x.status!=="rolled_back"?<button className="btn btn-ghost btn-sm" disabled={readOnly} onClick={()=>void rollback(x.id)}>Qaytarish</button>:null}</td></tr>)}</tbody></table></div>}</div>
  </section>;
}

type Insights={periodDays:number;settings:{firstResponseMinutes:number;autoAssignEnabled:boolean;reminderEnabled:boolean};totals:{leads:number;won:number;lost:number;unanswered:number;slaBreached:number;avgResponseMinutes:number|null};managers:{memberId?:string;name:string;leads:number;won:number;completed:number;lost:number;revenue:number;conversionPct:number;avgResponseMinutes:number|null}[]};
export function InsightsPage({show,readOnly}:{show:boolean;readOnly:boolean}){
  const [days,setDays]=useState(30);const [d,setD]=useState<Insights|null>(null);const [msg,setMsg]=useState("");
  async function load(){const r=await agencyApi<Insights>(`/crm/insights?days=${days}`);if(r.success){setD(r.data);setMsg("");}else setMsg(r.message||"Hisobot olinmadi");}
  useEffect(()=>{if(show)void load();},[show,days]);
  async function save(){if(!d)return;const r=await agencyApi<{settings:Insights["settings"]}>("/crm/settings",{method:"PUT",body:JSON.stringify(d.settings)});setMsg(r.success?"SLA sozlamalari saqlandi.":r.message||"Saqlanmadi");if(r.success)void load();}
  const kpis=useMemo(()=>d?[['Yangi lidlar',d.totals.leads],['Yopilgan',d.totals.won],['Javobsiz SLA',d.totals.unanswered],['O‘rtacha javob',d.totals.avgResponseMinutes==null?'—':`${d.totals.avgResponseMinutes} daq.`]]:[],[d]);
  return <section className={`view${show?" active":""}`}>{msg?<div className="note">{msg}</div>:null}<div style={box}><div style={{display:"flex",gap:12,justifyContent:"space-between",alignItems:"center",flexWrap:"wrap"}}><div><h3>SLA va menejer KPI</h3><p className="muted">Javobsiz lidlarni aniqlaydi, vazifa yaratadi va sotuv natijasini o‘lchaydi.</p></div><select value={days} onChange={(e)=>setDays(Number(e.target.value))}><option value={7}>7 kun</option><option value={30}>30 kun</option><option value={90}>90 kun</option><option value={365}>1 yil</option></select></div></div>{d?<><div style={grid}>{kpis.map(([a,b])=><div style={box} key={String(a)}><small>{a}</small><h2>{b}</h2></div>)}</div><div style={box}><h3>Avtomatlashtirish</h3><div style={grid}><label className="fld"><span>Birinchi javob SLA (daqiqa)</span><input type="number" min={5} max={1440} value={d.settings.firstResponseMinutes} onChange={(e)=>setD({...d,settings:{...d.settings,firstResponseMinutes:Number(e.target.value)}})}/></label><label><input type="checkbox" checked={d.settings.autoAssignEnabled} onChange={(e)=>setD({...d,settings:{...d.settings,autoAssignEnabled:e.target.checked}})}/> Yangi lidlarni round-robin biriktirish</label><label><input type="checkbox" checked={d.settings.reminderEnabled} onChange={(e)=>setD({...d,settings:{...d.settings,reminderEnabled:e.target.checked}})}/> SLA buzilganda vazifa yaratish</label></div><button className="btn btn-primary" disabled={readOnly} onClick={()=>void save()}>Sozlamalarni saqlash</button></div><div style={box}><h3>Menejerlar samaradorligi</h3><div style={{overflowX:"auto"}}><table className="tbl"><thead><tr><th>Menejer</th><th>Lid</th><th>Yopilgan</th><th>Yo‘qotilgan</th><th>Konversiya</th><th>Javob</th><th>Aylanma</th></tr></thead><tbody>{d.managers.map((m)=><tr key={m.memberId||"none"}><td><b>{m.name}</b></td><td>{m.leads}</td><td>{m.won+m.completed}</td><td>{m.lost}</td><td>{m.conversionPct}%</td><td>{m.avgResponseMinutes==null?"—":`${m.avgResponseMinutes} daq.`}</td><td>{formatMoney(m.revenue)}</td></tr>)}</tbody></table></div></div></>:null}</section>;
}

type WaState={configured:boolean;connected:boolean;displayPhone?:string;phoneNumberId?:string;wabaId?:string;welcome:string};
export function WhatsAppPage({show,readOnly}:{show:boolean;readOnly:boolean}){
  const [st,setSt]=useState<WaState|null>(null);const [token,setToken]=useState("");const [phoneNumberId,setPhone]=useState("");const [wabaId,setWaba]=useState("");const [welcome,setWelcome]=useState("");const [msg,setMsg]=useState("");const [templates,setTemplates]=useState<{id:string;name:string;language:string;status:string;category:string}[]>([]);
  async function load(){const r=await agencyApi<WaState>("/whatsapp");if(r.success){setSt(r.data);setWelcome(r.data.welcome||"");setPhone(r.data.phoneNumberId||"");setWaba(r.data.wabaId||"");}}
  useEffect(()=>{if(show)void load();},[show]);
  async function connect(){const r=await agencyApi<WaState>("/whatsapp/connect",{method:"POST",body:JSON.stringify({token,phoneNumberId,wabaId})});setMsg(r.success?"WhatsApp muvaffaqiyatli ulandi.":r.message||"Ulanmadi");if(r.success){setToken("");void load();}}
  async function disconnect(){if(!confirm("WhatsApp ulanishi uzilsinmi?"))return;const r=await agencyApi("/whatsapp/disconnect",{method:"POST"});setMsg(r.success?"Ulanish uzildi.":r.message||"Xato");void load();}
  async function saveWelcome(){const r=await agencyApi("/whatsapp/welcome",{method:"PUT",body:JSON.stringify({text:welcome})});setMsg(r.success?"Salomlashish saqlandi.":r.message||"Xato");}
  async function loadTemplates(){const r=await agencyApi<{templates:typeof templates}>("/whatsapp/templates");if(r.success)setTemplates(r.data.templates);else setMsg(r.message||"Shablonlar olinmadi");}
  return <section className={`view${show?" active":""}`}><div style={box}><h3>WhatsApp Cloud API</h3><p className="muted">Rasmiy Meta Cloud API. Kelgan xabar avtomatik lidga aylanadi va yagona CRM chatida ko‘rinadi.</p>{msg?<p>{msg}</p>:null}{st?.connected?<><p><b>Ulangan:</b> {st.displayPhone||st.phoneNumberId}</p><button className="btn btn-ghost" disabled={readOnly} onClick={()=>void disconnect()}>Ulanishni uzish</button></>:<div style={grid}><label className="fld"><span>Permanent access token</span><input type="password" value={token} onChange={(e)=>setToken(e.target.value)}/></label><label className="fld"><span>Phone Number ID</span><input value={phoneNumberId} onChange={(e)=>setPhone(e.target.value)}/></label><label className="fld"><span>WABA ID</span><input value={wabaId} onChange={(e)=>setWaba(e.target.value)}/></label><button className="btn btn-primary" disabled={readOnly||!token||!phoneNumberId||!wabaId} onClick={()=>void connect()}>Ulash va webhook’ga obuna bo‘lish</button></div>}</div>{st?.connected?<><div style={box}><h3>Avto-salomlashish</h3><textarea rows={4} value={welcome} onChange={(e)=>setWelcome(e.target.value)} placeholder="Assalomu alaykum! So‘rovingiz qabul qilindi."/><br/><button className="btn btn-primary" disabled={readOnly} onClick={()=>void saveWelcome()}>Saqlash</button></div><div style={box}><h3>Meta shablonlari</h3><button className="btn btn-ghost" onClick={()=>void loadTemplates()}>Yangilash</button>{templates.map((t)=><div key={t.id} style={{padding:"10px 0",borderBottom:"1px solid var(--border,#eee)"}}><b>{t.name}</b> · {t.language} · {t.status} · {t.category}</div>)}</div></>:null}</section>;
}
