events { worker_connections 1024; }

http {
  upstream backend {
    server backend:4000;
  }

  upstream website {
    server website:3000;
  }

  server {
    listen 80;
    server_name localhost travelorai.com www.travelorai.com admin.travelorai.com agency.travelorai.com;

    location /api/ {
      proxy_pass http://backend;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_cache_bypass $http_upgrade;
    }

    location /health {
      proxy_pass http://backend/api/v1/health;
    }

    location / {
      proxy_pass http://website;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_cache_bypass $http_upgrade;
    }
  }
}
