INSERT INTO "Poi" (
  "id", "name", "city", "slug", "type", "subtype", "lat", "lng", "info",
  "description", "imageUrl", "rating", "ratingCount", "priceLevel", "price",
  "icon", "openingHours", "source", "sourceUrl", "lastVerifiedAt",
  "confidenceScore", "verifiedBy", "createdAt", "updatedAt"
) VALUES
  (
    'poi_landing_registon',
    'Registon maydoni',
    'Samarqand',
    'registon-maydoni',
    'landmark',
    'historic',
    39.6547,
    66.9758,
    'Samarqandning eng mashhur tarixiy maydoni va Silk Road ramzi.',
    'Registon maydoni O''zbekiston bo''ylab birinchi safar qilayotgan sayohatchilar uchun eng muhim landmarklardan biri.',
    NULL,
    4.9,
    1200,
    NULL,
    NULL,
    'landmark',
    NULL,
    'admin',
    NULL,
    CURRENT_TIMESTAMP,
    0.86,
    'admin',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'poi_landing_kalon',
    'Kalon minorasi',
    'Buxoro',
    'kalon-minorasi',
    'landmark',
    'historic',
    39.7759,
    64.4151,
    'Buxoro eski shahri markazidagi tarixiy minora.',
    'Kalon minorasi Buxoro marshrutida piyoda ko''rish uchun qulay va eng taniqli nuqtalardan biri.',
    NULL,
    4.8,
    860,
    NULL,
    NULL,
    'landmark',
    NULL,
    'admin',
    NULL,
    CURRENT_TIMESTAMP,
    0.84,
    'admin',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'poi_landing_ichan_qala',
    'Ichan-Qal''a',
    'Xiva',
    'ichan-qala',
    'landmark',
    'heritage',
    41.3782,
    60.3593,
    'Xivaning devor bilan o''ralgan tarixiy eski shahri.',
    'Ichan-Qal''a Xorazm madaniyati, minoralar, madrasa va craft yo''nalishlari uchun asosiy joy.',
    NULL,
    4.9,
    980,
    NULL,
    NULL,
    'landmark',
    NULL,
    'admin',
    NULL,
    CURRENT_TIMESTAMP,
    0.86,
    'admin',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'poi_landing_chorsu',
    'Chorsu bozori',
    'Toshkent',
    'chorsu-bozori',
    'landmark',
    'bazaar',
    41.3267,
    69.2345,
    'Toshkentdagi mahalliy bozor, food tour va suvenirlar uchun qulay nuqta.',
    'Chorsu bozori Toshkentda mahalliy taomlar, bozor madaniyati va qisqa city walk uchun tavsiya qilinadi.',
    NULL,
    4.7,
    740,
    NULL,
    NULL,
    'landmark',
    NULL,
    'admin',
    NULL,
    CURRENT_TIMESTAMP,
    0.8,
    'admin',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("id") DO NOTHING;
